CC = gcc
CFLAGS = -Wall -O2 -fomit-frame-pointer -ffast-math -funroll-loops

include makefile.common

EXENAME = FoFLyricConvert

all : $(EXENAME)

$(EXENAME) : $(OFILES)
	gcc $(OFILES) $(CFLAGS) $(LIBS) -o $(EXENAME)

clean:
	@rm *.o
	@rm $(EXENAME)
	@echo Cleanup complete!
