CC = gcc
CFLAGS = -O2 -fomit-frame-pointer -ffast-math -arch i386 -arch ppc -static-libgcc -mmacosx-version-min=10.5 -funroll-loops
LIBS = -L/opt/local/lib

include makefile.common

EXENAME = foflc

all : $(EXENAME)

$(EXENAME) : $(OFILES)
	gcc $(OFILES) $(CFLAGS) $(LIBS) -o $(EXENAME)

clean:
	@rm -f *.o
	@rm -f $(EXENAME)
	@echo Cleanup complete!
