CC = i586-mingw32msvc-gcc
CFLAGS = -Wall -O2 -fomit-frame-pointer -ffast-math -funroll-loops

include makefile.common

EXENAME = foflc.exe

all : $(EXENAME)

$(EXENAME) : $(OFILES)
	i586-mingw32msvc-gcc $(OFILES) $(CFLAGS) $(LIBS) -o $(EXENAME)

clean:
	@rm *.o
	@rm $(EXENAME)
	@echo Cleanup complete!
