CC = gcc
CFLAGS = -O2 -fomit-frame-pointer -ffast-math -arch i386 -arch ppc -mmacosx-version-min=10.4 -isysroot /Developer/SDKs/MacOSX10.4u.sdk -funroll-loops -Ialogg/decoder/libogg/include -Ialogg/decoder/libvorbis/include -Ialogg/include -I/opt/local/include
LIBS = -L/opt/local/lib `allegro-config --frameworks`

OFILES = modules/ocd3d.o modules/wfsel.o modules/gametime.o modules/g-idle.o main.o player.o config.o window.o dialog.o legacy.o midi.o ini.o song.o note.o beat.o event.o gui.o undo.o mix.o control.o editor.o feedback.o
ALOGGOFILES = alogg/decoder/libvorbis/lib/analysis.o alogg/decoder/libvorbis/lib/bitrate.o alogg/decoder/libogg/src/bitwise.o alogg/decoder/libvorbis/lib/block.o alogg/decoder/libvorbis/lib/codebook.o alogg/decoder/libvorbis/lib/envelope.o alogg/decoder/libvorbis/lib/floor0.o alogg/decoder/libvorbis/lib/floor1.o alogg/decoder/libogg/src/framing.o alogg/decoder/libvorbis/lib/info.o alogg/decoder/libvorbis/lib/lpc.o alogg/decoder/libvorbis/lib/lsp.o alogg/decoder/libvorbis/lib/mapping0.o alogg/decoder/libvorbis/lib/mdct.o alogg/decoder/libvorbis/lib/psy.o alogg/decoder/libvorbis/lib/registry.o alogg/decoder/libvorbis/lib/res0.o alogg/decoder/libvorbis/lib/sharedbook.o alogg/decoder/libvorbis/lib/smallft.o alogg/decoder/libvorbis/lib/synthesis.o alogg/decoder/libvorbis/lib/vorbisfile.o alogg/decoder/libvorbis/lib/window.o alogg/src/alogg.o
AGUPOFILES = agup/aalg.o agup/aase.o agup/abeos.o  agup/abitmap.o  agup/agtk.o  agup/agup.o  agup/ans.o  agup/aphoton.o  agup/awin95.o
EXENAME = eof

../bin/$(EXENAME) : $(OFILES) $(AGUPOFILES) $(ALOGGOFILES)
	gcc $(OFILES) $(AGUPOFILES) $(ALOGGOFILES) $(CFLAGS) $(LIBS) -o ../bin/$(EXENAME)

clean:
	@rm *.o
	@rm modules/*.o
	@rm agup/*.o
	@rm alogg/src/*.o
	@rm alogg/decoder/libvorbis/lib/*.o
	@rm alogg/decoder/libogg/src/*.o
	@echo Cleanup complete!
